services:
  goodnews:
    image: masardon/goodnews:alpha
    ports:
      - "8000:8000"
    volumes:
      - /opt/data:/app/data
      - /opt/creds:/app/creds
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:8080"
    environment:
      - DOZZLE_BASE=/dozzle
